version: '3.8'

services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=Str0ngP@ssw0rd!
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    networks:
      - autolot-net

  apilot-api:
    build:
      context: .
      dockerfile: AutoLot.Api/Dockerfile
    ports:
      - "5021:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - autolot-net
    depends_on:
      - database
networks:
  autolot-net:
